version: '3'
services:

  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    volumes:
      # mount agency translation data to ./sftp-data
      - ./sftp-data:/home/agency/share
      # mount public keys used by agency
      - ./sftp-keys:/home/agency/.ssh/keys:ro
    # run on port 2222
    ports:
      - "2222:22"
    # create user 'agency'
    command: agency::1001

  s3:
    image: minio/minio:latest
    container_name: s3
    # persistent data
    volumes:
      - ./s3-data:/data
    # run on port 9000
    ports:
      - "9000:9000"
    # set credentials
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: letmeinplease
    # s3: serve root
    command: server /data

  nginx:
    depends_on: ['s3']
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"

  setup_s3:
    depends_on: ['s3']
    image: minio/mc:latest
    container_name: setup_s3
    volumes:
      - ./scripts:/scripts
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: letmeinplease
    entrypoint: /scripts/setup_minio.sh
