version: '3'
services:

  sftp:
    image: atmoz/sftp:alpine
    container_name: sftp
    volumes:
      # user config
      - ./sftp-config/users.conf:/etc/sftp/users.conf:ro
      # mount agency translation data to ./sftp-data
      - ./sftp-data:/home
      # mount host keys
      - ./sftp-keys/host/ed25519_key:/etc/ssh/ssh_host_ed25519_key
      - ./sftp-keys/host/rsa_key:/etc/ssh/ssh_host_rsa_key
      # mount public keys used by agency
      - ./sftp-keys/agency1/rsa_key.pub:/home/agency1/.ssh/keys/rsa_key.pub
      - ./sftp-keys/agency2/rsa_key.pub:/home/agency2/.ssh/keys/rsa_key.pub
      - ./sftp-keys/agency3/rsa_key.pub:/home/agency3/.ssh/keys/rsa_key.pub
    # run on port 2222
    ports:
      - "2222:22"

  s3:
    image: minio/minio:latest
    container_name: s3
    # persistent data
    volumes:
      - ./s3-data:/data
    # run on port 9000
    ports:
      - "9000:9000"
    # set credentials
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: letmeinplease
    # s3: serve root
    command: server /data

  nginx:
    depends_on: ['s3']
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:80"

  setup_s3:
    depends_on: ['s3']
    image: minio/mc:latest
    container_name: setup_s3
    volumes:
      - ./scripts:/scripts
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: letmeinplease
    entrypoint: /scripts/setup_minio.sh
