name: Taxi Test

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      TAXI_ENV: local
      LOGLEVEL: debug
      
    steps:
    - name: "Setup ruby 2.6"
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x

    - uses: actions/checkout@v1

    - uses: actions/cache@v1
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: "Install Gems"
      run: |
        gem install bundler:2.1.4
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3

    - name: "Run Taxi Tests"
      run: ./test.sh ci

    - name: "Output logs"
      if: always()
      run: |
        docker logs sftp
        ls -al dev/
        echo "DATA"
        ls -al dev/sftp-data/
        ls -al dev/sftp-data/*
        echo "KEYS"
        ls -al dev/sftp-keys/
        ls -al dev/sftp-keys/*

